version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    volumes:
      - ./public:/usr/share/nginx/public:cached
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/app:cached
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: production
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
